[project]
name = "odoo-addons-oca-community-data-files"
version = "18.0.20241119.0"
dependencies = [
    "odoo-addon-l10n_eu_product_adr==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
